"""
BigQuery Gold Layer provisioning tool.
Creates the Gold dataset and tables/views directly in BigQuery.
"""

import logging
from datetime import datetime, timezone

from google.cloud import bigquery
from google.cloud.bigquery import SchemaField, TimePartitioning, RangePartitioning, PartitionRange
from google.api_core.exceptions import GoogleAPIError, Conflict

from .gcs_tools import _DESIGN_CACHE   # shared in-process cache

logger = logging.getLogger(__name__)


# ── Type mapping: Silver field_type → BigQuery SchemaField type ───────────────
_BQ_TYPE_MAP = {
    "STRING": "STRING", "BYTES": "BYTES",
    "INTEGER": "INT64", "INT64": "INT64",
    "FLOAT": "FLOAT64", "FLOAT64": "FLOAT64",
    "NUMERIC": "NUMERIC", "BIGNUMERIC": "BIGNUMERIC",
    "BOOLEAN": "BOOL", "BOOL": "BOOL",
    "TIMESTAMP": "TIMESTAMP", "DATE": "DATE", "TIME": "TIME", "DATETIME": "DATETIME",
    "RECORD": "RECORD", "STRUCT": "STRUCT",
    "GEOGRAPHY": "GEOGRAPHY", "JSON": "JSON",
}


def _make_schema(columns: list[dict]) -> list[SchemaField]:
    """Convert column specs from generate_gold_design() into BQ SchemaField list."""
    fields = []
    for col in columns:
        bq_type = _BQ_TYPE_MAP.get(col.get("type", "STRING"), "STRING")
        mode = col.get("mode", "NULLABLE")
        if mode not in ("NULLABLE", "REQUIRED", "REPEATED"):
            mode = "NULLABLE"
        fields.append(
            SchemaField(
                name=col["name"],
                field_type=bq_type,
                mode=mode,
                description=col.get("description", ""),
            )
        )
    # Append standard audit columns
    audit_fields = [
        SchemaField("dw_insert_timestamp", "TIMESTAMP", mode="NULLABLE",
                    description="Row insert timestamp (pipeline audit)"),
        SchemaField("dw_update_timestamp", "TIMESTAMP", mode="NULLABLE",
                    description="Row update timestamp (pipeline audit)"),
        SchemaField("dw_source_system",    "STRING",    mode="NULLABLE",
                    description="Source pipeline identifier"),
        SchemaField("dw_batch_id",         "STRING",    mode="NULLABLE",
                    description="Pipeline batch / run UUID"),
        SchemaField("dw_created_by",       "STRING",    mode="NULLABLE",
                    description="Session user who ran the pipeline"),
    ]
    fields.extend(audit_fields)
    return fields


def _apply_partitioning(table: bigquery.Table, part_rec: dict) -> bigquery.Table:
    strategy = part_rec.get("strategy", "INGESTION_TIME")
    col = part_rec.get("column")
    if strategy == "TIME" and col:
        granularity = part_rec.get("granularity", "DAY")
        gran_map = {"DAY": "DAY", "HOUR": "HOUR", "MONTH": "MONTH", "YEAR": "YEAR"}
        table.time_partitioning = TimePartitioning(
            type_=gran_map.get(granularity, "DAY"),
            field=col,
        )
    elif strategy == "RANGE" and col:
        table.range_partitioning = RangePartitioning(
            field=col,
            range_=PartitionRange(start=0, end=10000, interval=100),
        )
    else:
        # Ingestion-time partitioning
        table.time_partitioning = TimePartitioning(type_="DAY")
    return table


def create_gold_layer(
    project_id: str,
    gold_dataset_id: str,
    location: str,
    design_id: str,
) -> dict:
    """
    Create the Gold layer BigQuery dataset and all tables/views designed by
    generate_gold_design().

    Call this after generate_gold_design(). Use the design_id it returned.

    Args:
        project_id:      GCP project ID.
        gold_dataset_id: Name of the Gold layer dataset to create (e.g. 'gold_layer').
        location:        BigQuery dataset location (e.g. 'US', 'EU', 'us-central1').
        design_id:       The design_id string returned by generate_gold_design().

    Returns:
        dict with success flag, created tables list, and any errors.
    """
    design = _DESIGN_CACHE.get(design_id)
    if not design:
        return {
            "success": False,
            "message": (
                f"No design found for design_id='{design_id}'. "
                "Call generate_gold_design() first and use the returned design_id."
            ),
            "created_tables": [],
            "errors": [],
        }

    gold_tables: list[dict] = design.get("gold_tables", [])
    client = bigquery.Client(project=project_id)
    created_tables = []
    errors = []

    # ── 1. Create (or confirm) the Gold dataset ───────────────────────────────
    dataset_ref = bigquery.Dataset(f"{project_id}.{gold_dataset_id}")
    dataset_ref.location = location
    dataset_ref.description = (
        f"Gold layer dataset generated by DM Agent on "
        f"{datetime.now(tz=timezone.utc).isoformat()}"
    )
    dataset_ref.labels = {"layer": "gold", "managed_by": "dm_agent"}
    try:
        dataset = client.create_dataset(dataset_ref, exists_ok=True)
        logger.info("Dataset ready: %s", dataset.full_dataset_id)
    except GoogleAPIError as e:
        return {
            "success": False,
            "message": f"Failed to create dataset '{gold_dataset_id}': {e}",
            "created_tables": [],
            "errors": [str(e)],
        }

    # ── 2. Create lineage_log table ───────────────────────────────────────────
    lineage_schema = [
        SchemaField("run_id",            "STRING",    mode="REQUIRED"),
        SchemaField("source_table",      "STRING",    mode="REQUIRED"),
        SchemaField("target_table",      "STRING",    mode="REQUIRED"),
        SchemaField("rows_processed",    "INT64",     mode="NULLABLE"),
        SchemaField("run_started_at",    "TIMESTAMP", mode="NULLABLE"),
        SchemaField("run_completed_at",  "TIMESTAMP", mode="NULLABLE"),
        SchemaField("status",            "STRING",    mode="NULLABLE"),
        SchemaField("error_message",     "STRING",    mode="NULLABLE"),
        SchemaField("pipeline_name",     "STRING",    mode="NULLABLE"),
        SchemaField("batch_id",          "STRING",    mode="NULLABLE"),
        SchemaField("dw_insert_timestamp","TIMESTAMP",mode="NULLABLE"),
    ]
    lineage_table_ref = bigquery.Table(
        f"{project_id}.{gold_dataset_id}.lineage_log", schema=lineage_schema
    )
    lineage_table_ref.time_partitioning = TimePartitioning(
        type_="DAY", field="dw_insert_timestamp"
    )
    lineage_table_ref.clustering_fields = ["source_table", "target_table", "status"]
    lineage_table_ref.description = "Gold layer pipeline lineage and audit log"
    try:
        client.create_table(lineage_table_ref, exists_ok=True)
        created_tables.append(f"{project_id}.{gold_dataset_id}.lineage_log")
    except GoogleAPIError as e:
        errors.append(f"lineage_log: {e}")

    # ── 3. Create Gold tables ─────────────────────────────────────────────────
    for tspec in gold_tables:
        gold_table_id = tspec["gold_table_id"]
        full_id = f"{project_id}.{gold_dataset_id}.{gold_table_id}"
        columns: list[dict] = tspec.get("columns", [])
        part_rec: dict = tspec.get("partitioning", {})
        clust_fields: list[str] = tspec.get("clustering", [])
        role: str = tspec.get("role", "dimension")

        try:
            schema = _make_schema(columns)

            # Add SCD Type 2 columns for dimensions
            if role == "dimension":
                schema += [
                    SchemaField("eff_start_date", "DATE",    mode="NULLABLE",
                                description="SCD2 effective start date"),
                    SchemaField("eff_end_date",   "DATE",    mode="NULLABLE",
                                description="SCD2 effective end date"),
                    SchemaField("is_current",     "BOOL",    mode="NULLABLE",
                                description="SCD2 current record flag"),
                ]

            bq_table = bigquery.Table(full_id, schema=schema)
            bq_table = _apply_partitioning(bq_table, part_rec)
            if clust_fields:
                # Clustering columns must exist in schema
                schema_names = {f.name for f in schema}
                valid_clust = [c for c in clust_fields if c in schema_names]
                if valid_clust:
                    bq_table.clustering_fields = valid_clust[:4]

            bq_table.description = (
                f"Gold layer {role} table. "
                f"Source: {tspec.get('source_table', '')}. "
                f"Generated by DM Agent."
            )
            bq_table.labels = {
                "layer": "gold",
                "role": role,
                "managed_by": "dm_agent",
            }

            client.create_table(bq_table, exists_ok=True)
            created_tables.append(full_id)
            logger.info("Created table: %s", full_id)

            # ── Aggregation view for fact tables ──────────────────────────────
            agg_view_id = tspec.get("aggregation_view")
            if role == "fact" and agg_view_id:
                _create_agg_view(
                    client, project_id, gold_dataset_id,
                    agg_view_id, full_id, columns, created_tables, errors
                )

        except GoogleAPIError as e:
            logger.error("Error creating %s: %s", full_id, e)
            errors.append(f"{gold_table_id}: {e}")

    # ── 4. Summary ────────────────────────────────────────────────────────────
    success = len(errors) == 0
    return {
        "success": success,
        "project_id": project_id,
        "gold_dataset_id": gold_dataset_id,
        "location": location,
        "created_tables": created_tables,
        "table_count": len(created_tables),
        "errors": errors,
        "message": (
            f"Gold layer provisioned: {len(created_tables)} tables/views created "
            f"in '{project_id}.{gold_dataset_id}'."
            + (f" Errors: {len(errors)}." if errors else "")
        ),
    }


def _create_agg_view(
    client: bigquery.Client,
    project_id: str,
    gold_dataset_id: str,
    view_id: str,
    source_table: str,
    columns: list[dict],
    created_tables: list,
    errors: list,
) -> None:
    """Create a daily summary view for a fact table."""
    date_cols = [
        c["name"] for c in columns
        if c.get("type") in ("DATE", "TIMESTAMP", "DATETIME")
    ]
    numeric_cols = [
        c["name"] for c in columns
        if c.get("type") in ("FLOAT", "FLOAT64", "NUMERIC", "BIGNUMERIC", "INTEGER", "INT64")
        and any(kw in c["name"].lower()
                for kw in ("amount", "qty", "quantity", "count", "revenue",
                           "cost", "price", "value", "total", "sum"))
    ]
    if not date_cols or not numeric_cols:
        return

    date_col   = date_cols[0]
    metric_col = numeric_cols[0]
    full_view  = f"{project_id}.{gold_dataset_id}.{view_id}"

    view_query = f"""
SELECT
    DATE({date_col})      AS report_date,
    COUNT(*)              AS record_count,
    SUM({metric_col})     AS total_{metric_col},
    AVG({metric_col})     AS avg_{metric_col},
    MIN({metric_col})     AS min_{metric_col},
    MAX({metric_col})     AS max_{metric_col}
FROM `{source_table}`
GROUP BY 1
ORDER BY 1 DESC
""".strip()

    try:
        view = bigquery.Table(full_view)
        view.view_query = view_query
        view.description = f"Daily summary view for {source_table}"
        client.create_table(view, exists_ok=True)
        created_tables.append(full_view)
        logger.info("Created view: %s", full_view)
    except GoogleAPIError as e:
        errors.append(f"{view_id}: {e}")