"""Generate readable BigQuery Standard SQL DDL from a Proposal.

DDL is generated deterministically from the validated model (not free-text
from the LLM) so it is always syntactically consistent and safe to run. Keys
are declared as NOT ENFORCED constraints, which BigQuery accepts and query
optimisation can use.
"""

from __future__ import annotations

from .models import Partitioning, PartitionType, Proposal, Table


def _fq(project: str, dataset: str, table: str) -> str:
    return f"`{project}.{dataset}.{table}`"


def _column_line(col) -> str:
    parts = [f"  {col.name} {col.type}"]
    if not col.nullable or col.is_primary_key:
        parts.append("NOT NULL")
    line = " ".join(parts)
    if col.description:
        desc = col.description.replace('"', "'")
        line += f' OPTIONS(description="{desc}")'
    return line


def _partition_clause(table: Table) -> str | None:
    p: Partitioning = table.partitioning
    if p.type == PartitionType.NONE or not p.column:
        return None

    col_type = next(
        (c.type.upper() for c in table.columns if c.name == p.column), None
    )
    if col_type is None:
        # Partition column isn't in the table; skip rather than emit bad DDL.
        return None
    gran = (p.granularity or "DAY").upper()

    if p.type == PartitionType.TIME:
        # Time partitioning is only valid on genuine temporal columns.
        if col_type == "DATE":
            expr = p.column if gran == "DAY" else f"DATE_TRUNC({p.column}, {gran})"
        elif col_type == "TIMESTAMP":
            expr = f"TIMESTAMP_TRUNC({p.column}, {gran})"
        elif col_type == "DATETIME":
            expr = f"DATETIME_TRUNC({p.column}, {gran})"
        else:
            # e.g. an INT64 date key (YYYYMMDD): cannot time-partition.
            # Caller falls back to clustering on this column.
            return None
        return f"PARTITION BY {expr}"

    if p.type == PartitionType.INTEGER_RANGE and p.range_start is not None:
        return (
            f"PARTITION BY RANGE_BUCKET({p.column}, "
            f"GENERATE_ARRAY({p.range_start}, {p.range_end}, {p.range_interval or 1}))"
        )
    return None


def generate_table_ddl(project: str, proposal: Proposal, table: Table) -> str:
    fq = _fq(project, proposal.gold_dataset, table.name)
    lines = [_column_line(c) for c in table.columns]

    if table.primary_key:
        lines.append(f"  PRIMARY KEY ({table.primary_key}) NOT ENFORCED")

    for fk in table.foreign_keys:
        ref = _fq(project, proposal.gold_dataset, fk.references_table)
        lines.append(
            f"  FOREIGN KEY ({fk.column}) REFERENCES {ref}({fk.references_column}) NOT ENFORCED"
        )

    ddl = f"CREATE TABLE IF NOT EXISTS {fq}\n(\n" + ",\n".join(lines) + "\n)"

    col_names = {c.name for c in table.columns}
    # Only cluster by columns that actually exist in the table.
    cluster_cols = [c for c in table.clustering if c in col_names]

    part = _partition_clause(table)
    if part:
        ddl += f"\n{part}"
    else:
        # A partition was requested but is unusable (e.g. INT64 date key or a
        # missing column). Fall back to clustering on that column so we still
        # get pruning, if it exists and isn't already clustered.
        p = table.partitioning
        if (
            p.type != PartitionType.NONE
            and p.column
            and p.column in col_names
            and p.column not in cluster_cols
        ):
            cluster_cols.append(p.column)

    if cluster_cols:
        # BigQuery allows at most 4 clustering columns.
        ddl += f"\nCLUSTER BY {', '.join(cluster_cols[:4])}"
    if table.description:
        desc = table.description.replace('"', "'")
        ddl += f'\nOPTIONS(description="{desc}")'
    return ddl + ";"


def generate_ddl(project: str, proposal: Proposal) -> tuple[str, list[str]]:
    """Return (full_script, [statements]).

    Dimensions are created before facts so fact FK references resolve.
    """
    statements: list[str] = []
    blocks: list[str] = [
        "-- =====================================================================",
        f"-- Gold layer DDL for dataset: {proposal.gold_dataset}",
        f"-- Source: {proposal.source_project}.{proposal.source_dataset}",
        "-- Generated by Data Modeler Agent. Review before running.",
        "-- =====================================================================",
        "",
    ]

    ordered = [*proposal.dimensions, *proposal.facts]
    for table in ordered:
        header = f"-- {table.table_type.value.upper()}: {table.name}"
        if table.grain:
            header += f"  (grain: {table.grain})"
        stmt = generate_table_ddl(project, proposal, table)
        statements.append(stmt)
        blocks.extend([header, stmt, ""])

    return "\n".join(blocks), statements
